### ISSUE TITLE
another os.UserConfigDir possibility, if you want

### ISSUE THREAD

**Issue by rwxrob** [Chaitanyabsprip/dotfiles#2] opened 2024-11-13 19:58 UTC
https://github.com/Chaitanyabsprip/dotfiles/blob/33ff03af60d56747239008ec45bc99ee165aaaa2/internal/core/embed/copy.go#L48

**Comment by chaitanyabsprip** [comment] 2024-11-13 20:16
Duplicate of #1

**Closed as completed by chaitanyabsprip** 2024-11-13 20:16 UTC
